// Auto-generated by tools/mkcard.py. Do not edit: re-run it.
//
// What the card file holds and in what order, for a build with CARDIMAGES on. The layout
// is set out in tools/mkcard.py; this only names the entries so the game can ask for one
// by name and check that the card it found was made by this build.

#pragma once
#include <stdint.h>

//the file the game looks for in the card's root
#define CARD_FILE_NAME "BLOCKDUD.DAT"

//the same name as a FAT directory entry holds it: eight characters then three, no dot,
//which is the form CHSd's fat::find takes
#define CARD_FILE_83 "BLOCKDUDDAT"

//every skin and picture name, hashed: a card made by another build has another stamp
#define CARD_STAMP 0xD7507E0CUL

//the sections of the container, by the name its table holds. Levels will be another one
#define CARD_SEC_IMAGES "IMGS"
#define CARD_SEC_LEVELS "LVLS"

//1 when any picture is kept as one colour a row, see FMT_ROWS. The game builds the
//code that draws one only then: a card without any is a game that need not carry it
#define CARD_HAS_ROWS 1

#define CARD_SKIN_COUNT 5
#define CARD_IMAGE_COUNT 30

//the skins, in the order the index holds them
enum CardSkin : uint8_t
{
	CARD_SKIN_DEFAULT = 0,
	CARD_SKIN_FLAT = 1,
	CARD_SKIN_KENNEY = 2,
	CARD_SKIN_TECH = 3,
	CARD_SKIN_TI_83 = 4,
};

//what each skin is called on screen
#define CARD_SKIN_NAMES { "Default", "Flat", "Kenney", "Tech", "Ti-83" }

//the pictures, in the order the index holds them within a skin
enum CardImage : uint8_t
{
	CARD_IMG_BACKGROUND = 0,
	CARD_IMG_BOX_TABLE_16_16 = 1,
	CARD_IMG_DOOR_TABLE_16_16 = 2,
	CARD_IMG_EARTHGRASSLEFT_TABLE_16_16 = 3,
	CARD_IMG_EARTHGRASSRIGHT_TABLE_16_16 = 4,
	CARD_IMG_EARTHLEFT_TABLE_16_16 = 5,
	CARD_IMG_EARTHMIDDLE_TABLE_16_16 = 6,
	CARD_IMG_EARTHRIGHT_TABLE_16_16 = 7,
	CARD_IMG_FLOATINGFLOOR_TABLE_16_16 = 8,
	CARD_IMG_FLOATINGFLOORLEFT_TABLE_16_16 = 9,
	CARD_IMG_FLOATINGFLOORMIDDLE_TABLE_16_16 = 10,
	CARD_IMG_FLOATINGFLOORRIGHT_TABLE_16_16 = 11,
	CARD_IMG_FLOOR_TABLE_16_16 = 12,
	CARD_IMG_FLOORLEFT_TABLE_16_16 = 13,
	CARD_IMG_FLOORRIGHT_TABLE_16_16 = 14,
	CARD_IMG_INTRO1 = 15,
	CARD_IMG_INTRO2 = 16,
	CARD_IMG_INTRO3 = 17,
	CARD_IMG_PLAYER_TABLE_16_16 = 18,
	CARD_IMG_ROOF1_TABLE_16_16 = 19,
	CARD_IMG_ROOF2_TABLE_16_16 = 20,
	CARD_IMG_ROOFCORNERBOTH_TABLE_16_16 = 21,
	CARD_IMG_ROOFCORNERLEFT_TABLE_16_16 = 22,
	CARD_IMG_ROOFCORNERRIGHT_TABLE_16_16 = 23,
	CARD_IMG_ROOFDOWNLEFT_TABLE_16_16 = 24,
	CARD_IMG_ROOFDOWNRIGHT_TABLE_16_16 = 25,
	CARD_IMG_STARTTOWER_TABLE_16_16 = 26,
	CARD_IMG_TITLESCREEN = 27,
	CARD_IMG_TOWER_TABLE_16_16 = 28,
	CARD_IMG_TOWERSHAFT_TABLE_16_16 = 29,
};

//1 when the card holds the level packs too, so the game reads them from there and not
//out of flash. 0 leaves everything about the levels as it was
#define CARD_HAS_LEVELS 1

#define CARD_LEVEL_COUNT 25

//the packs, in the order the index holds them, by the name the game knows
#define CARD_LEVEL_NAMES { "blockman/level1.lev", "blockman/level2.lev", "blockman/level3.lev", "blockman/level4.lev", "blockman/level5.lev", "blockman/level6.lev", "blockman/level7.lev", "blockman/level8.lev", "blockman/level9.lev", "blockman/level10.lev", "blockman/level11.lev", "blockman/level12.lev", "blockman/level13.lev", "blockman/level14.lev", "blockman/level15.lev", "blockman/level16.lev", "blockman/level17.lev", "blockman/level18.lev", "blockman/level19.lev", "blockman/level20.lev", "blockman/level21.lev", "davy/level1.lev", "davy/level2.lev", "davy/level3.lev", "davy/level4.lev" }

//how many levels each pack holds, the entries above being one flat list
#define CARD_LEVEL_PACKS 2
#define CARD_LEVEL_PACK_COUNTS { 21, 4 }
