#!/usr/bin/env python3
"""Convert the level files in assets/levels to source/blockdude_embedded/levels.h.

Every sub folder of assets/levels is a level pack, every .lev file in it a level.
A .lev file is a list of (type, x, y) byte triplets, it is stored as is followed by
the 0xFF 0xFF 0xFF end marker CWorldParts_Load reads up to.

Packs and levels are sorted naturally, so level2 comes after level1 and not after
level19, as level_data_files[pack][SelectedLevel - 1] is how the game finds a level.

Usage:
  python convert_levels.py            write levels.h
  python convert_levels.py --verify   build levels.h in memory and compare it with the
                                      current one, nothing is written
  --output FILE                       write (or verify) this file instead
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
LEVELS_DIR = os.path.join(ROOT, "assets", "levels")
OUTPUT = os.path.join(ROOT, "source", "blockdude_embedded", "levels.h")
BYTES_PER_LINE = 32
EOF_MARKER = b"\xFF\xFF\xFF"


def natural_key(name):
    """level2 < level10: digit runs compare as numbers."""
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", name)]


def c_name(pack, file_name):
    stem = os.path.splitext(file_name)[0]
    return "level_data_%s_%s_data" % (re.sub(r"\W", "_", pack), re.sub(r"\W", "_", stem))


def read_packs(levels_dir):
    """[(pack, [(file name, bytes), ...]), ...] in natural order."""
    packs = []
    for pack in sorted(os.listdir(levels_dir), key=natural_key):
        folder = os.path.join(levels_dir, pack)
        if not os.path.isdir(folder):
            continue
        levels = []
        for file_name in sorted(os.listdir(folder), key=natural_key):
            if not file_name.lower().endswith(".lev"):
                continue
            with open(os.path.join(folder, file_name), "rb") as f:
                data = f.read()
            if len(data) % 3:
                raise SystemExit("%s/%s: %d bytes is not a list of (type, x, y) triplets" % (pack, file_name, len(data)))
            if 0xFF in data[0::3]:
                raise SystemExit("%s/%s: a part of type 0xFF would be read as the end marker" % (pack, file_name))
            levels.append((file_name, data))
        packs.append((pack, levels))
    return packs


def build_header(packs, levels_dir):
    max_items = max(len(levels) for _, levels in packs)
    lines = [
        "// Auto-generated by tools/convert_levels.py",
        "// Source directory: %s" % os.path.relpath(levels_dir, ROOT).replace(os.sep, "/"),
        "// Access as: level_data_files[group_index][item_index]  (const uint8_t*)",
        "// Unused slots (groups with fewer than level_data_max_items files) are padded",
        "// with NULL so the array stays rectangular.",
        "// Each file's array is terminated with the marker bytes: 0xFF 0xFF 0xFF",
        "// (read until this byte sequence is encountered to find the end of the data)",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "// Index map:",
    ]
    for g, (pack, levels) in enumerate(packs):
        lines.append("//   [%d] %s/" % (g, pack))
        for i, (file_name, _) in enumerate(levels):
            lines.append("//       [%d] %s" % (i, file_name))
    lines.append("")

    for pack, levels in packs:
        for file_name, data in levels:
            body = data + EOF_MARKER
            lines.append("// %s/%s (%d bytes + 3-byte EOF marker)" % (pack, file_name, len(data)))
            lines.append("const uint8_t %s[] PLATFORM_PROGMEM = {" % c_name(pack, file_name))
            rows = ["    " + ", ".join("0x%02X" % b for b in body[off:off + BYTES_PER_LINE])
                    for off in range(0, len(body), BYTES_PER_LINE)]
            lines.append(",\n".join(rows))
            lines.append("};")
            lines.append("")

    lines.append("// 2D lookup table: level_data_files[group_index][item_index]")
    lines.append("const uint8_t* const level_data_files[%d][%d] = {" % (len(packs), max_items))
    rows = []
    for pack, levels in packs:
        names = [c_name(pack, file_name) for file_name, _ in levels]
        names += ["NULL"] * (max_items - len(names))
        rows.append("    { " + ", ".join(names) + " }")
    lines.append(",\n".join(rows))
    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"


def parse_header(text):
    """What the game gets out of a levels.h: the arrays (text and bytes) and the lookup table."""
    arrays = {}
    for m in re.finditer(r"(// [^\n]+\n)const uint8_t (\w+)\[\] PLATFORM_PROGMEM = \{\n(.*?)\n\};", text, re.S):
        arrays[m.group(2)] = {
            "text": m.group(0),
            "bytes": bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(3))),
        }
    m = re.search(r"level_data_files\[(\d+)\]\[(\d+)\] = \{\n(.*?)\n\};", text, re.S)
    table = None
    if m:
        rows = re.findall(r"\{ (.*?) \}", m.group(3))
        table = {"dims": (int(m.group(1)), int(m.group(2))), "rows": [r.split(", ") for r in rows]}
    return arrays, table


def verify(new_text, path):
    with open(path, "r", newline="") as f:
        old_text = f.read()
    new_arrays, new_table = parse_header(new_text)
    old_arrays, old_table = parse_header(old_text)
    ok = True

    if old_table is None:
        print("  no level_data_files table found in %s" % path)
        return False
    if new_table["dims"] != old_table["dims"]:
        ok = False
        print("  DIFFERS  table size %s, current file has %s" % (new_table["dims"], old_table["dims"]))
    for g, (new_row, old_row) in enumerate(zip(new_table["rows"], old_table["rows"])):
        for i, (new_name, old_name) in enumerate(zip(new_row, old_row)):
            if new_name != old_name:
                ok = False
                print("  DIFFERS  level_data_files[%d][%d] = %s, current file has %s" % (g, i, new_name, old_name))
    print("  lookup table %dx%d: %s" % (new_table["dims"] + ("identical" if ok else "differs",)))

    same = 0
    for name in sorted(set(new_arrays) | set(old_arrays), key=natural_key):
        if name not in old_arrays:
            ok = False
            print("  MISSING  %s is not in the current file" % name)
        elif name not in new_arrays:
            ok = False
            print("  EXTRA    %s is in the current file but made from no .lev file" % name)
        elif new_arrays[name]["bytes"] != old_arrays[name]["bytes"]:
            ok = False
            print("  DIFFERS  %s has other level data" % name)
        elif new_arrays[name]["text"] != old_arrays[name]["text"]:
            ok = False
            print("  DIFFERS  %s has the same bytes but is formatted differently" % name)
        else:
            same += 1
    print("  level arrays: %d of %d identical (data and text)" % (same, len(new_arrays)))

    if ok and new_text != old_text:
        print("  note: the file text differs outside the arrays and the table (generator line, index map")
        print("        comment or the order the arrays are defined in), this has no effect on the game")
    return ok


def main():
    parser = argparse.ArgumentParser(description="Convert assets/levels to levels.h")
    parser.add_argument("--verify", action="store_true", help="compare with the current levels.h, write nothing")
    parser.add_argument("--output", default=OUTPUT, help="levels.h to write or verify")
    args = parser.parse_args()

    packs = read_packs(LEVELS_DIR)
    text = build_header(packs, LEVELS_DIR)
    summary = ", ".join("%s %d" % (pack, len(levels)) for pack, levels in packs)

    if args.verify:
        print("verifying %s against assets/levels (%s)" % (os.path.relpath(args.output, ROOT), summary))
        ok = verify(text, args.output)
        print("everything matches" if ok else "there are differences")
        return 0 if ok else 1

    with open(args.output, "w", newline="\n") as f:
        f.write(text)
    print("wrote %s (%s)" % (os.path.relpath(args.output, ROOT), summary))
    return 0


if __name__ == "__main__":
    sys.exit(main())
